### PR TITLE
Updates dm6 download URL from current to FB2016_03

### PR DESCRIPTION
**Pull request by jfear**
Flybase just release 6.12. In the config files the url pointed to the 'current' directory which now has 6.12 and not 6.11. Fixed url to point to 6.11.

### CODE REVIEW

**Comment by christabone** [comment]
Just an FYI - we released 2016_04 yesterday if you'd like to update (it will be current until ~September 27th).

ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.12_FB2016_04/fasta/

**Comment by christabone** [comment]
Ah, my mistake, I see that you're keeping it on the older version. Please ignore my other comment. :)

**Comment by jfear** [comment]
Haha, already figured that out, it pointed out a bug in our reference
construction pipeline.

**Comment by jfear** [comment]
Thanks though, we like to keep version constant on a per project basis. Then when the project is complete we typically try to re-run with what ever is most current.

**Comment by daler** [comment]
thanks, good catch.

**Pull request merged**
